trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: RunCypressTests
    displayName: "Executar Cypress Tests em Paralelo no Mesmo Servidor"
    steps:
      - task: Docker@2
        inputs:
          command: 'build'
          dockerfile: 'Dockerfile'
          tags: 'cypress-tests'
          containerRegistry: ''

      - task: DockerCompose@0
        displayName: 'Executar Cypress em Paralelo via Docker Compose'
        inputs:
          containerRegistry: ''
          dockerComposeFile: 'docker-compose.yml'
          dockerComposeCommand: 'up' 
          projectName: 'cypress_parallel_tests'

      - task: DockerCompose@0
        displayName: 'Derrubar containers após os testes'
        inputs:
          containerRegistry: ''
          dockerComposeFile: 'docker-compose.yml'
          dockerComposeCommand: 'down'
