services:
  cypress_test_1:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - CYPRESS_baseUrl=https://www.saucedemo.com/
      - TEST_FILE=cypress\e2e\pages\FrontEnd\1_login.spec.js
    volumes:
      - cypress_cache:/root/.cache/Cypress
      - cypress_reports:/e2e/reports

  cypress_test_2:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - CYPRESS_baseUrl=https://www.saucedemo.com/
      - TEST_FILE=cypress\e2e\pages\FrontEnd\2_BuyAndCheckout.spec.js
    volumes:
      - cypress_cache:/root/.cache/Cypress
      - cypress_reports:/e2e/reports

# Definição dos volumes
volumes:
  cypress_cache:
  cypress_reports:
