name: Cypress Parallel Tests

on:
  push:
    branches: [ main ]

jobs:
  cypress-parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: cypress-tests

      - name: Iniciar containers
        run: docker compose up -d

      - name: Executar Cypress (paralelo)
        run: |
          docker compose up \
            --abort-on-container-exit \
            --exit-code-from cypress_test_1

      - name: Teardown dos containers
        if: always()
        run: docker compose down
