name: Cypress Parallel Tests

on:
  push:
    branches:
      - main

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build da imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false        
          tags: cypress-tests

      - name: Iniciar containers
        run: docker-compose up -d

      - name: Executar Cypress em paralelo
        run: |
          # substitua `service_name` pelo nome do seu serviço no docker-compose.yml
          docker-compose up --abort-on-container-exit --exit-code-from service_name

      - name: Teardown dos containers
        if: always()
        run: docker-compose down
